package collections

fun main() {

    // USE MAP TO GENERATE A LIST WHOSE ELEMENTS ARE GENERATED BY
    // APPLYING THE GIVEN LAMBDA FUNCTION TO THE ELEMENTS OF THE
    // EXISTING COLLECTION

    val authors = Library.books
        .map {
            it.authors
        }
        .map {
            it.joinToString {
                it.name
            }
        }
        .joinToString(separator="\n")

    //println(authors)
    val titleAndAuthors = Library.books
        .map {
            val authors = it.authors.joinToString { it.name }
            "${it.title} by $authors"
        }
        .joinToString(separator="\n")

    //println(titleAndAuthors)

    /* Note that this is better achieved with a forEach loop. If you're
    only accessing the fields of the object (here its a book) but not
    transforming it, and the only other thing you need is an index, then
    forEach is simpler and more concise */
    val booksWithIndex = Library.books
        .mapIndexed { index, book ->
            "${index+1}: ${book.title}"
        }
        .joinToString("\n")
    println(booksWithIndex)
}